#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <string.h>
#include <sys/stat.h>
#include "macro.h"
#include "common.h"
#include "cJSON.h"
#include "json.h"
#include "base64.h"

//Define
//#define PERFORMANCE

//Functions
static void writePermissions(cJSON *elPermissions, int grantLocal, cJSON *elLocalRanges, char *szIPExternal, FILE *pfM) {
//Permissions: [ "public", "hardware", "local", "admin", "user" ]
	char szB[] = "\t\t<RequireAny>\n";
	fwrite(szB, strlen(szB), 1, pfM);
	if (grantLocal) {
		char sz[256];
		cJSON *range = NULL;
		cJSON_ArrayForEach(range, elLocalRanges) {
			snprintf(sz, sizeof(sz), "\t\t\tRequire ip %s\n", range->valuestring);
			fwrite(sz, strlen(sz), 1, pfM);
		}
		if (strlen(szIPExternal) > 0) {
			snprintf(sz, sizeof(sz), "\t\t\tRequire ip %s\n", szIPExternal);
			fwrite(sz, strlen(sz), 1, pfM);
		}
	}
	int hasUser = 0;
	cJSON *permission = NULL;
	cJSON_ArrayForEach(permission, elPermissions) {
		char sz[256];
		if (strcmp(permission->valuestring, "public") == 0) {
			char sz[] = "\t\t\tRequire all granted\n";
			fwrite(sz, strlen(sz), 1, pfM);
			break;	
		} else if (strcmp(permission->valuestring, "hardware") == 0) {
			char sz[] = "\t\t\tRequire local\n";
			fwrite(sz, strlen(sz), 1, pfM);
		} else if (strcmp(permission->valuestring, "user") == 0) {
			hasUser = 1;
			char sz[] = "\t\t\tRequire AppModulePermission user\n";
			fwrite(sz, strlen(sz), 1, pfM);
		}
	}
	if (hasUser == 0) {
		char sz[] = "\t\t\tRequire AppModulePermission admin\n";
		fwrite(sz, strlen(sz), 1, pfM);
	}
	char szE[] = "\t\t</RequireAny>\n";
	fwrite(szE, strlen(szE), 1, pfM);
}

static void writeSymlinks(int b, FILE *pfM) {
	char sz[256];
	sprintf(sz, "\t\tOptions %sFollowSymLinks\n", b ? "+" : "-");
	fwrite(sz, strlen(sz), 1, pfM);
}

static void writeMultiViews(int b, FILE *pfM) {
	char sz[256];
	sprintf(sz, "\t\tOptions %sMultiViews\n", b ? "+" : "-");
	fwrite(sz, strlen(sz), 1, pfM);
}

static void writeIndexes(int b, FILE *pfM) {
	char sz[256];
	sprintf(sz, "\t\tOptions %sIndexes\n", b ? "+" : "-");
	fwrite(sz, strlen(sz), 1, pfM);
}

static void writeDirectoryIndex(char *s, FILE *pfM) {
	char sz[256];
	snprintf(sz, sizeof(sz), "\t\tDirectoryIndex %s\n", s);
	fwrite(sz, strlen(sz), 1, pfM);
}

static void writeLog(char *name, FILE *pfM) {
	char sz[256];
	snprintf(sz, sizeof(sz), "\tCustomLog /var/log/apache2/module-%s.log combined\n", name);
	fwrite(sz, strlen(sz), 1, pfM);
}


static void fillServer(int tabN, cJSON *elModule, cJSON *elModule2, cJSON *fqdn, FILE *pfM) {
	jsonPrintArray(tabN, "ServerName ", "ServerAlias ", strcmp(elModule->string, "apache2") == 0 ? "" : elModule->string, fqdn, "\n", pfM);
	cJSON *i = NULL;
	cJSON *a = NULL;
	a = cJSON_GetObjectItem(elModule, "alias");
	if (a)
		cJSON_ArrayForEach(i, a)
			jsonPrintArray(tabN, "ServerAlias ", "ServerAlias ",  i->valuestring, fqdn, "\n", pfM);
	a = cJSON_GetObjectItem(elModule2, "alias");
	if (a)
		cJSON_ArrayForEach(i, a)
			jsonPrintArray(tabN, "ServerAlias ", "ServerAlias ",  i->valuestring, fqdn, "\n", pfM);
}

void rewrite_(char *st, int port, FILE *pfM) {
	char sz[512];
	char port_[16];
	strcpy(port_, "");
	if (port > 0)
		sprintf(port_, ":%d", port);
	snprintf(sz, sizeof(sz), "\
	RewriteCond %%{HTTP_HOST} ^(\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})(:\\d+)?$\n\
	RewriteRule ^/m/%s.* %%{REQUEST_SCHEME}://%%1%s [NC,L]\n", st, port_);
	fwrite(sz, strlen(sz), 1, pfM);
}

void rewrite(cJSON *el_Module, cJSON *el_Module2, int port, FILE *pfM) {
	rewrite_(el_Module->string, port, pfM);
	cJSON *i = NULL;
	cJSON *a = NULL;
	a = cJSON_GetObjectItem(el_Module, "alias");
	if (a)
		cJSON_ArrayForEach(i, a)
			rewrite_(i->valuestring, port, pfM);
	a = cJSON_GetObjectItem(el_Module2, "alias");
	if (a)
		cJSON_ArrayForEach(i, a)
			rewrite_(i->valuestring, port, pfM);
}

void buildApache2Conf(cJSON *cloud, cJSON *modulesDefault, cJSON *modules, cJSON *fqdn, char *szIPExternal) {
#ifdef PERFORMANCE
	struct timespec ts_proc1;
	clock_gettime(CLOCK_REALTIME, &ts_proc1);
#endif
#ifdef DESKTOP
	FILE *pfP = fopen("/tmp/ports.conf", "w");
#else
	FILE *pfP = fopen(ADMIN_PATH "apache2/ports.conf", "w");
#endif
	char sz[4096];
	strcpy(sz, "\
<IfModule ssl_module>\n\
	Listen 443\n\
</IfModule>\n");
	fwrite(sz, strlen(sz), 1, pfP);
#ifdef DESKTOP
	FILE *pfM = fopen("/tmp/main.conf", "w");
#else
	FILE *pfM = fopen(ADMIN_PATH "apache2/main.conf", "w");
#endif
	cJSON *ap = cJSON_GetObjectItem(modulesDefault, "apache2");
	cJSON *ap2 = cJSON_GetObjectItem(modulesDefault, "apache2");
	int grantLocal = cJSON_IsTrue(cJSON_GetObjectItem(cJSON_GetObjectItem(cloud, "security"), "grantLocalPermission"));
	cJSON *elLocalRanges = cJSON_GetObjectItem(ap, "localRanges");
	snprintf(sz, sizeof(sz), "\
#This file is automatically generated and overwritten unless there is a boolean property\n\
#Apache2->overwrite: true in /disk/admin/modules/_config_/_modules_.json\n\n\
#\n\
#Relation between /usr/local/modules/_core_/web/assets/modulesdefault.json [1] and /disk/admin/_config_/_modules_.json [2]\n\
#Overwritten values by [2] on [1]: enabled, permissions, DirectoryIndex, FollowSymLink, Indexes\n\
#Values added up by [2] after [1]: addConfig, addLineInDirectory\n\
#\n\
LoadModule app_module /usr/local/modules/apache2/mod_app.so\n\
AppCloudName %s\n\
AppJwkPem /disk/admin/modules/betterauth/jwk-pub.pem\n\
LoadModule app_ip_module /usr/local/modules/apache2/mod_app_ip.so\n\n\
GlobalLog /var/log/apache2/_all_.log vhost_combined\n\
AppIPEnabled %s\n\
AppALEnabled %s\n\
\n\
<Macro Macro_Redirect $1>\n\
	RewriteEngine On\n\
	ProxyRequests Off\n\
	ProxyPreserveHost on\n\
	ProxyAddHeaders on\n\
	RequestHeader set \"X-Forwarded-Proto\" expr=%%{REQUEST_SCHEME}\n\
	ProxyVia On\n\
	ProxyPass /_app_/auth/ http://localhost:8091/auth/\n\
	AliasMatch /_app_/disabled.php /usr/local/modules/apache2/pages/disabled.php\n\
	AliasMatch /_app_/error.php /usr/local/modules/apache2/pages/error.php\n\
	AliasMatch /_app_/unauthorized.php /usr/local/modules/apache2/pages/unauthorized.php\n\
	<Directory /usr/local/modules/apache2/pages>\n\
		Require all granted\n\
	</Directory>\n\
	Alias /_app_ /usr/local/modules/apache2/web\n\
	<Directory /usr/local/modules/apache2/web>\n\
		RewriteBase /\n\
		RewriteRule ^index\\.html$ - [L]\n\
		RewriteCond %%{REQUEST_FILENAME} !-f\n\
		RewriteCond %%{REQUEST_FILENAME} !-d\n\
		RewriteRule . /_app_/index.html [L]\n\
		Require all granted\n\
	</Directory>\n\
	ErrorDocument 400 /_app_/error.php?e=400\n\
	ErrorDocument 401 /_app_/unauthorized.php?m=$1\n\
	ErrorDocument 403 /_app_/unauthorized.php?m=$1\n\
	ErrorDocument 404 /_app_/error.php?e=404\n\
	ErrorDocument 429 /_app_/error.php?e=429\n\
	ErrorDocument 500 /_app_/error.php?e=500\n\
	ErrorDocument 501 /_app_/error.php?e=501\n\
	ErrorDocument 502 /_app_/error.php?e=502\n\
	ErrorDocument 503 /_app_/error.php?e=503\n\
	ErrorDocument 504 /_app_/error.php?e=504\n\
	ProxyPass /_app_/ !\n\
</Macro>\n\
<Macro Macro_SSL>\n\
	Include /usr/local/modules/apache2/options-ssl-apache.conf\n\
	SSLCertificateFile /disk/admin/modules/letsencrypt/fullchain.pem\n\
	SSLCertificateKeyFile /disk/admin/modules/letsencrypt/privkey.pem\n\
</Macro>\n", cJSON_GetStringValue2(cJSON_GetObjectItem(cloud, "info"), "name"), cJSON_IsTrue(cJSON_GetObjectItem(cJSON_GetObjectItem(cloud, "security"), "updateRemoteIP")) ? "on" : "off", cJSON_IsTrue(cJSON_GetObjectItem(cJSON_GetObjectItem(cloud, "security"), "autoLogin")) ? "on" : "off");
	fwrite(sz, strlen(sz), 1, pfM);
	strcpy(sz, "<Macro Macro_Rewrite>\n");
	fwrite(sz, strlen(sz), 1, pfM);
	cJSON *elModule;
	cJSON_ArrayForEach(elModule, modulesDefault) {
		if (cJSON_HasObjectItem(elModule, "web")) {
			cJSON *elModule2 = cJSON_GetObjectItem(modules, elModule->string);
			int localPort = (int)cJSON_GetNumberValue(cJSON_GetObjectItem(elModule, "localPort"));
			rewrite(elModule, elModule2, localPort, pfM);
		}
	}
	strcpy(sz, "\
	RewriteCond %{HTTP_HOST} ^(app\\.|www\\.)?(.*)\n\
	RewriteRule ^/m/([^/]+)(.*) %{REQUEST_SCHEME}://$1.%2$2 [NC,L]\n\
</Macro>\n\n\n");
	fwrite(sz, strlen(sz), 1, pfM);

	int firstTime = 1;
begin:
	cJSON_ArrayForEach(elModule, modulesDefault) {
		if (firstTime && strcmp(elModule->string, "apache2") != 0)
			continue;
		if (!firstTime && strcmp(elModule->string, "apache2") == 0)
			continue;
		if (cJSON_HasObjectItem(elModule, "web")) {
			cJSON *elModule2 = cJSON_GetObjectItem(modules, elModule->string);
			char path[128];
			if (cJSON_HasObjectItem(elModule, "path"))
				strcpy(path, cJSON_GetStringValue2(elModule, "path"));
			else
				snprintf(path, sizeof(path), "/usr/local/modules/%s", elModule->string);
			snprintf(sz, sizeof(sz), "\
<Macro Macro_%s>\n\
	AppModuleName %s\n\
	Use Macro_Redirect %s\n", elModule->string, elModule->string, elModule->string);
			fwrite(sz, strlen(sz), 1, pfM);
			cJSON *elEnabled = cJSON_GetObjectItem(elModule, "enabled");
			if (cJSON_HasObjectItem(elModule2, "enabled"))
				elEnabled = cJSON_GetObjectItem(elModule2, "enabled");
			int ready = !cJSON_HasObjectItem(elModule, "setup") || cJSON_HasObjectItem(elModule2, "setupDone");
			if (cJSON_IsTrue(elEnabled) && ready) {
				cJSON *elPermissions = cJSON_GetObjectItem(elModule, "permissions");
				if (cJSON_HasObjectItem(elModule2, "permissions"))
					elPermissions = cJSON_GetObjectItem(elModule2, "permissions");

				if (cJSON_HasObjectItem(elModule, "addConfigBegin")) {
					snprintf(sz, sizeof(sz), "\t%s\n", cJSON_GetStringValue2(elModule, "addConfigBegin"));
					fwrite(sz, strlen(sz), 1, pfM);
				}
				if (cJSON_HasObjectItem(elModule2, "addConfigBegin")) {
					snprintf(sz, sizeof(sz), "\t%s\n", cJSON_GetStringValue2(elModule2, "addConfigBegin"));
					fwrite(sz, strlen(sz), 1, pfM);
				}

				int doDirectory = 1;
				if (cJSON_HasObjectItem(elModule, "reverseProxy")) {
					cJSON *elReverseProxy;
					cJSON_ArrayForEach(elReverseProxy, cJSON_GetObjectItem(elModule, "reverseProxy")) {
						char *type_ = cJSON_GetStringValue2(elReverseProxy, "type");
						char *path_ = cJSON_GetStringValue2(elReverseProxy, "path");
						char *path2_ = cJSON_GetStringValue2(elReverseProxy, "path2");
						if (!path2_)
							path2_ = path_;
						int reversePort = (int)cJSON_GetNumberValue(cJSON_GetObjectItem(elReverseProxy, "port"));
						if (strcmp(type_, "http") == 0) {
							snprintf(sz, sizeof(sz), "\tProxyPass %s http://localhost:%d%s\n\tProxyPassReverse %s http://localhost:%d%s\n", path_, reversePort, path2_, path_, reversePort, path2_);
							if (strcmp(path_, "/") == 0)
								doDirectory = 0;
						}
						else if (strcmp(type_, "ws") == 0)
							snprintf(sz, sizeof(sz), "\tRewriteCond %%{HTTP:Upgrade} websocket [NC]\n\tRewriteCond %%{HTTP:Connection} upgrade [NC]\n\tRewriteRule ^%s(.*) ws://localhost:%d%s$1 [P,L]\n", path_, reversePort, path_);
						fwrite(sz, strlen(sz), 1, pfM);
					}
					strcpy(sz, "\t<Proxy *>\n");
					fwrite(sz, strlen(sz), 1, pfM);
					writePermissions(elPermissions, grantLocal, elLocalRanges, szIPExternal, pfM);
					strcpy(sz, "\t</Proxy>\n");
					fwrite(sz, strlen(sz), 1, pfM);
				}
				if (doDirectory) {
					snprintf(sz, sizeof(sz), "\tDocumentRoot %s\n\t<Directory %s>\n", path, path);
					fwrite(sz, strlen(sz), 1, pfM);

					if (cJSON_HasObjectItem(elModule, "addLineInDirectory")) {
						snprintf(sz, sizeof(sz), "\t\t%s\n", cJSON_GetStringValue2(elModule, "addLineInDirectory"));
						fwrite(sz, strlen(sz), 1, pfM);
					}
					if (cJSON_HasObjectItem(elModule2, "addLineInDirectory")) {
						snprintf(sz, sizeof(sz), "\t\t%s\n", cJSON_GetStringValue2(elModule2, "addLineInDirectory"));
						fwrite(sz, strlen(sz), 1, pfM);
					}
					writePermissions(elPermissions, grantLocal, elLocalRanges, szIPExternal, pfM);
					if (cJSON_HasObjectItem(elModule2, "directoryIndex"))
						writeDirectoryIndex(cJSON_GetStringValue2(elModule2, "directoryIndex"), pfM);
					else if (cJSON_HasObjectItem(elModule, "directoryIndex"))
						writeDirectoryIndex(cJSON_GetStringValue2(elModule, "directoryIndex"), pfM);
					if (cJSON_HasObjectItem(elModule2, "followSymLinks"))
						writeSymlinks(cJSON_IsTrue(cJSON_GetObjectItem(elModule2, "followSymLinks")), pfM);
					else if (cJSON_GetObjectItem(elModule, "followSymLinks"))
						writeSymlinks(cJSON_IsTrue(cJSON_GetObjectItem(elModule, "followSymLinks")), pfM);
					if (cJSON_HasObjectItem(elModule2, "multiViews"))
						writeMultiViews(cJSON_IsTrue(cJSON_GetObjectItem(elModule2, "multiViews")), pfM);
					else if (cJSON_GetObjectItem(elModule, "multiViews"))
						writeMultiViews(cJSON_IsTrue(cJSON_GetObjectItem(elModule, "multiViews")), pfM);
					if (cJSON_HasObjectItem(elModule2, "indexes"))
						writeIndexes(cJSON_IsTrue(cJSON_GetObjectItem(elModule2, "indexes")), pfM);
					else if (cJSON_GetObjectItem(elModule, "indexes"))
						writeIndexes(cJSON_IsTrue(cJSON_GetObjectItem(elModule, "indexes")), pfM);

					strcpy(sz, "\t</Directory>\n");
					fwrite(sz, strlen(sz), 1, pfM);
				}

				if (cJSON_HasObjectItem(elModule, "addConfigEnd")) {
					snprintf(sz, sizeof(sz), "\t%s\n", cJSON_GetStringValue2(elModule, "addConfigEnd"));
					fwrite(sz, strlen(sz), 1, pfM);
				}
				if (cJSON_HasObjectItem(elModule2, "addConfigEnd")) {
					snprintf(sz, sizeof(sz), "\t%s\n", cJSON_GetStringValue2(elModule2, "addConfigEnd"));
					fwrite(sz, strlen(sz), 1, pfM);
				}

				if (strcmp(elModule->string, "apache2") == 0 || strcmp(elModule->string, "_core_") == 0) {
					strcpy(sz, "\tUse Macro_Rewrite\n");
					fwrite(sz, strlen(sz), 1, pfM);
				}
				if (cJSON_HasObjectItem(elModule, "autoLoginNoGzip")) {
					cJSON *al = NULL;
					cJSON_ArrayForEach(al, cJSON_GetObjectItem(elModule, "autoLoginNoGzip")) {
						sprintf(sz, "\tSetEnvIf Request_URI %s no_gzip\n", al->valuestring);
						fwrite(sz, strlen(sz), 1, pfM);
					}
					strcpy(sz, "\tRequestHeader unset Accept-Encoding env=no_gzip\n");
					fwrite(sz, strlen(sz), 1, pfM);
				}
			} else {
				snprintf(sz, sizeof(sz), "\
	RewriteCond %%{REQUEST_URI} !^/_app_/disabled.php$\n\
	RewriteRule ^/.*$ /_app_/disabled.php?m=%s%s [PT,L]\n", elModule->string, !ready ? "&notSetup" : "");
				fwrite(sz, strlen(sz), 1, pfM);
			}
			writeLog(elModule->string, pfM);
			strcpy(sz, "</Macro>\n");
			fwrite(sz, strlen(sz), 1, pfM);

			int localPort = (int)cJSON_GetNumberValue(cJSON_GetObjectItem(elModule, "localPort"));
			sprintf(sz, "Listen %d\n", localPort);
			fwrite(sz, strlen(sz), 1, pfP);
			snprintf(sz, sizeof(sz), "<VirtualHost *:%d>\n\tUse Macro_%s\n</VirtualHost>\n", localPort, elModule->string);
			fwrite(sz, strlen(sz), 1, pfM);

			strcpy(sz, "<VirtualHost *:80>\n");
			fwrite(sz, strlen(sz), 1, pfM);
			fillServer(1, elModule, elModule2, fqdn, pfM);
			snprintf(sz, sizeof(sz), "\tUse Macro_%s\n</VirtualHost>\n", elModule->string);
			fwrite(sz, strlen(sz), 1, pfM);

			strcpy(sz, "<IfModule mod_ssl.c>\n\t<VirtualHost *:443>\n");
			fwrite(sz, strlen(sz), 1, pfM);
			fillServer(2, elModule, elModule2, fqdn, pfM);
			snprintf(sz, sizeof(sz), "\t\tUse Macro_%s\n\t\tUse Macro_SSL\n\t</VirtualHost>\n</IfModule>\n", elModule->string);
			fwrite(sz, strlen(sz), 1, pfM);

			strcpy(sz, "\n\n");
			fwrite(sz, strlen(sz), 1, pfM);
		}
		if (firstTime) {
			firstTime = 0;
			goto begin;
		}
	}
	fclose(pfP);
	fclose(pfM);
#ifdef PERFORMANCE
	struct timespec ts_proc2;
	clock_gettime(CLOCK_REALTIME, &ts_proc2);
	PRINTF("Apache2_conf: %4.1fms\n", (float)deltaTime(ts_proc2, ts_proc1));
#endif
}

void buildApache2ConfBeforeSetup() {
#ifdef DESKTOP
		FILE *pfP = fopen("/tmp/ports.conf", "w");
#else
		FILE *pfP = fopen(ADMIN_PATH "apache2/ports.conf", "w");
#endif
		char sz[1024];
		strcpy(sz, "\
Listen 80\n\
<IfModule ssl_module>\n\
	Listen 443\n\
</IfModule>\n");
		fwrite(sz, strlen(sz), 1, pfP);
		fclose(pfP);
#ifdef DESKTOP
		FILE *pfM = fopen("/tmp/main.conf", "w");
#else
		FILE *pfM = fopen(ADMIN_PATH "apache2/main.conf", "w");
#endif
		strcpy(sz, "\
<VirtualHost *:80>\n\
	RewriteEngine on\n\
	RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]\n\
</VirtualHost>\n\
<VirtualHost *:443>\n\
	Alias /_app_ /usr/local/modules/apache2/web\n\
	RewriteEngine On\n\
	RewriteCond %{HTTP:Upgrade} websocket [NC]\n\
	RewriteCond %{HTTP:Connection} upgrade [NC]\n\
	RewriteRule ^/ws(.*) ws://localhost:8094/ws$1 [P,L]\n\
	RewriteCond %{REQUEST_URI} !^/_app_ [NC]\n\
	RewriteRule ^(.*)$ /_app_/setup [R=301,L]\n\
	RewriteRule ^/_app_/login$ /_app_/setup [R=301,L]\n\
	<Directory /usr/local/modules/apache2/web>\n\
		RewriteEngine On\n\
		RewriteBase /_app_\n\
		RewriteCond %{REQUEST_FILENAME} !-f\n\
		RewriteCond %{REQUEST_FILENAME} !-d\n\
		RewriteRule . /_app_/index.html [L]\n\
		Require all granted\n\
	</Directory>\n\
	Include /usr/local/modules/apache2/options-ssl-apache.conf\n\
	SSLCertificateFile /usr/local/modules/apache2/self-fullchain.pem\n\
	SSLCertificateKeyFile /usr/local/modules/apache2/self-privkey.pem\n\
</VirtualHost>");
		fwrite(sz, strlen(sz), 1, pfM);
		fclose(pfM);
}
